# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        dotnet-version: [ '6.0.x' ]

        
    steps:
    - name: Checkout .NET Solution
      uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore src/Polly.Contrib.Hedging.sln
    - name: Build
      run: dotnet build --no-restore src/Polly.Contrib.Hedging.sln
    - name: Test
      run: dotnet test --no-build --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}" src/Polly.Contrib.Hedging.sln
