# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        dotnet-version: ['6.0.x' ]

    steps:
    - name: Checkout .NET Solution
      uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore src/Polly.Contrib.Hedging.sln
    - name: Build
      run: dotnet build --no-restore src/Polly.Contrib.Hedging.sln
      
    - name: Test
      run: dotnet test --no-build --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}" src/Polly.Contrib.Hedging.Specs/Polly.Contrib.Hedging.Specs.csproj   
    - name: Generate test coverage file
      uses: b3b00/coverlet-action@1.1.9
      with:
        testProject: 'src/Polly.Contrib.Hedging.Specs/Polly.Contrib.Hedging.Specs.csproj'
        output: 'coverlet/'
        outputFormat: 'lcov'
        threshold: 90
    - name: Generate Code Coverage report
      id: code-coverage
      uses: barecheck/code-coverage-action@v1
      with:
        barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
        lcov-file: "src/Polly.Contrib.Hedging.Specs/coverlet/coverage.net6.info"
        send-summary-comment: true
        show-annotations: "warning"

  mutation:
    name: Mutation tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: ['6.0.x' ]
    steps:
    - name: Checkout .NET Solution
      uses: actions/checkout@v3
        - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore src/Polly.Contrib.Hedging.sln
    - name: Build
      run: dotnet build --no-restore src/Polly.Contrib.Hedging.sln
    - name: stryker dotnet
      uses: naveen497/actions@0.0.1
